import type { CertificationPracticeModule, Domain } from '../../core/types'
import { diagnosticQuestionIds, questions } from './questions'

export const domains: Domain[] = [
  { id: 'D1', title: 'Fundamentals of AI and ML', weight: 20, objectives: ['AI concepts', 'Use cases', 'ML lifecycle and metrics'] },
  { id: 'D2', title: 'Fundamentals of Generative AI', weight: 24, objectives: ['GenAI concepts', 'Capabilities and limits', 'AWS GenAI services'] },
  { id: 'D3', title: 'Applications of Foundation Models', weight: 28, objectives: ['Model selection and customization', 'Prompt engineering', 'RAG and agents', 'Evaluation'] },
  { id: 'D4', title: 'Guidelines for Responsible AI', weight: 14, objectives: ['Responsible dimensions', 'Transparent and explainable AI'] },
  { id: 'D5', title: 'Security, Compliance, and Governance', weight: 14, objectives: ['Secure AI systems', 'Governance and compliance'] },
]

export const examFacts = {
  version: '1.1', publicationDate: '2026-04-30', questions: 65, minutes: 90, scored: 50, unscored: 15, passingScore: 700,
}

export const examAllocation = { D1: 13, D2: 16, D3: 18, D4: 9, D5: 9 }
export const practiceScoreDisclaimer = 'Scores are raw practice percentages. They are not AWS scaled scores and do not predict a pass.'

export const requiredV11Topics = [
  'agentic-ai', 'inference-patterns', 'traditional-ml-vs-fm', 'pipeline-differentiation',
  'genai-benefits', 'token-pricing', 'context-engineering', 'mcp', 'agentcore', 'strands-agents',
  'kiro', 'amazon-quick', 'aws-transform', 'distillation', 'prompt-management', 'human-in-loop-evaluation',
  'llm-as-judge', 'business-alignment-metrics', 'open-source-data-licensing', 'explainability-tools',
  'human-centered-design', 'shared-responsibility', 'encryption-in-transit', 'data-leakage-prevention',
  'ai-interaction-logging', 'guardrails', 'hallucination-detection', 'aurora-in-scope',
] as const

export const aifPracticeModule: CertificationPracticeModule = {
  code: 'AIF-C01',
  domains,
  exam: { questionCount: examFacts.questions, minutes: examFacts.minutes, allocation: examAllocation },
  questions,
  diagnosticQuestionIds,
  practiceScoreDisclaimer,
}

export const serviceMap = [
  ['Build with foundation models', 'Amazon Bedrock', 'Managed access to FMs plus Knowledge Bases, Agents, Guardrails, Model Evaluation, and Prompt Management. Does not build or train custom models from scratch — that is SageMaker AI.'],
  ['Build and train ML', 'Amazon SageMaker AI', 'End-to-end ML development, training, deployment, monitoring, Clarify, Model Cards, and JumpStart. Does not serve managed third-party FMs — that is Bedrock.'],
  ['Label training data', 'Amazon SageMaker Ground Truth', 'Creates labeled datasets with human and automated labeling workflows. Labels training data; does not review production predictions — that is A2I.'],
  ['Detect bias / explain predictions', 'Amazon SageMaker Clarify', 'Detects bias and produces per-prediction explanations (feature attributions). Explains a single model; does not label data or compare foundation models — that is Bedrock Model Evaluation.'],
  ['Store and share reusable features', 'Amazon SageMaker Feature Store', 'Central repository to store, version, and share features across training and serving. Stores features; does not generate or select them (feature engineering) or label data.'],
  ['Start from ready-made models and templates', 'Amazon SageMaker JumpStart', 'Pretrained models and solution templates to accelerate building. Offers starting points; does not detect bias (Clarify) or serve managed FMs (Bedrock).'],
  ['Human review of low-confidence predictions', 'Amazon Augmented AI (A2I)', 'Routes low-confidence ML predictions to human reviewers and returns their decisions. Reviews production predictions; does not label training data — that is Ground Truth.'],
  ['Managed retrieval for RAG', 'Amazon Bedrock Knowledge Bases', 'Ingests documents and manages retrieval to ground model responses. Manages retrieval; does not itself change model behavior — that is fine-tuning.'],
  ['Compare and evaluate foundation models', 'Amazon Bedrock Model Evaluation', 'Evaluates and compares FMs on quality and responsibility dimensions. Compares models; does not explain a single prediction — that is Clarify.'],
  ['Filter harmful or denied content in outputs', 'Amazon Bedrock Guardrails', 'Filters harmful content, denied topics, and sensitive information in inputs and outputs. A policy layer that complements IAM and application controls; does not replace them.'],
  ['Version and reuse prompts', 'Amazon Bedrock Prompt Management', 'Versions, stores, and reuses prompt templates with variables. Manages prompts; does not evaluate models or retrieve knowledge.'],
  ['Run and operate agents at scale', 'Amazon Bedrock AgentCore', 'Runtime, memory, identity, gateway, observability, and policy for production agents. Operates agents built with any framework; does not author them — that is Strands Agents.'],
  ['Build agents and tools (SDK)', 'Strands Agents', 'Open-source model-driven SDK for composing agents and tools. Build-time SDK; does not provide production runtime, identity, or observability — that is AgentCore.'],
  ['Conversational interfaces / chatbots', 'Amazon Lex', 'Builds conversational chatbots with speech and text understanding. Powers conversation; does not translate (Translate) or synthesize speech (Polly).'],
  ['Sentiment / entities / key phrases from text', 'Amazon Comprehend', 'Prebuilt NLP for sentiment, entities, key phrases, and language detection. Analyzes text; does not transcribe speech (Transcribe) or extract document structure (Textract).'],
  ['Speech to text', 'Amazon Transcribe', 'Converts audio into text. Transcribes speech; does not synthesize speech (Polly) or translate.'],
  ['Text to speech', 'Amazon Polly', 'Converts text into lifelike speech. Synthesizes speech; does not transcribe audio (Transcribe).'],
  ['Language translation', 'Amazon Translate', 'Translates text between languages. Translates; does not understand conversation flow (Lex) or analyze sentiment (Comprehend).'],
  ['Structured text extraction from documents', 'Amazon Textract', 'Extracts text, forms, and tables from scanned documents. Extracts document structure; does not analyze images or video (Rekognition).'],
  ['Image and video analysis', 'Amazon Rekognition', 'Detects objects, faces, and text and moderates images and video. Analyzes visual media; does not extract document forms or tables (Textract).'],
  ['Personalized recommendations', 'Amazon Personalize', 'Builds personalized recommendation models from user interaction data. Recommends; purpose-built, so it does not replace a general custom-training pipeline (SageMaker AI).'],
  ['Business insights', 'Amazon Quick', 'AI-powered workspace for search, research, business intelligence, and automation. Business-user workspace; does not provide production agent runtime (AgentCore).'],
  ['Enterprise assistance', 'Amazon Q', 'Role-aware generative assistance for business and developer work. Assists enterprise users; does not build or train models.'],
  ['Vector storage', 'Amazon S3 Vectors', 'Purpose-built vector storage with S3 economics for semantic search and RAG. Stores and queries vectors; does not generate embeddings or manage retrieval pipelines (Knowledge Bases).'],
  ['Relational and vector-aware data', 'Amazon Aurora', 'Managed relational database in scope; Aurora PostgreSQL can support vector-oriented application patterns. A durable data layer; not a GenAI service or FM API.'],
  ['Modernization', 'AWS Transform', 'Agentic AI service for transforming applications and infrastructure at scale. Modernizes systems; does not provide the IDE (Kiro) or the agent SDK (Strands Agents).'],
  ['AI development environment', 'Kiro', 'Agentic IDE focused on specification-driven software development. A development environment; does not run production agents (AgentCore).'],
  ['Recording API activity for audit', 'AWS CloudTrail', 'Records API calls for audit. Records who called what; does not show operational metrics (CloudWatch).'],
  ['Operational metrics and logs', 'Amazon CloudWatch', 'Metrics, logs, and alarms for operational telemetry. Monitors; does not record the identity behind API calls (CloudTrail).'],
  ['Encryption keys', 'AWS KMS', 'Manages encryption keys for data at rest. Manages keys; does not store or rotate secrets (Secrets Manager).'],
  ['Store and rotate secrets', 'AWS Secrets Manager', 'Stores and rotates secrets. Stores secrets; does not manage the keys themselves (KMS).'],
  ['Evaluate resource configuration against rules', 'AWS Config', 'Evaluates resource configuration against rules. Audits configuration; does not provide compliance reports (Artifact).'],
  ['Compliance reports on demand', 'AWS Artifact', 'Provides on-demand compliance reports and agreements. Supplies reports; does not audit API activity (CloudTrail).'],
  ['Discover sensitive data in S3', 'Amazon Macie', 'Discovers and classifies sensitive data in S3. Finds sensitive data; does not encrypt it (KMS) or control access (IAM).'],
  ['Least-privilege access control', 'AWS IAM', 'Roles, policies, and least-privilege access. Grants access; does not log activity (CloudTrail) or monitor (CloudWatch).'],
  ['Private connectivity to services', 'AWS PrivateLink', 'Private connectivity between VPCs and AWS services. Connects privately; does not provide encryption keys (KMS).'],
]

export const azureTransfers = [
  ['Azure AI Foundry / Azure OpenAI', 'Amazon Bedrock', 'Transfer the managed-model-catalog intuition, but learn Bedrock-specific features and names.'],
  ['Azure Machine Learning', 'Amazon SageMaker AI', 'Both cover the ML lifecycle; exam answers depend on the AWS product boundary.'],
  ['Microsoft Entra ID / RBAC', 'AWS IAM', 'Transfer least privilege and role-based access; use AWS principals, policies, and roles.'],
  ['Azure Key Vault', 'AWS KMS + Secrets Manager', 'KMS manages encryption keys; Secrets Manager stores and rotates secrets.'],
  ['Azure Monitor / Activity Log', 'CloudWatch / CloudTrail', 'CloudWatch covers metrics and logs; CloudTrail records API activity.'],
]

export const glossary = [
  ['Agentic AI', 'AI systems that plan and use tools to pursue goals across multiple steps.'],
  ['BERTScore', 'Semantic text evaluation based on contextual embeddings.'],
  ['BLEU', 'N-gram precision-oriented metric commonly used for translation.'],
  ['Context engineering', 'Designing the complete information environment supplied to a model, including instructions, history, tools, and retrieved data.'],
  ['Distillation', 'Training a smaller student model to reproduce useful behavior from a larger teacher model.'],
  ['Embedding', 'Numeric vector representing semantic meaning.'],
  ['FM', 'Foundation model: a broad model adaptable to many downstream tasks.'],
  ['Hallucination', 'A fluent output that is unsupported, incorrect, or fabricated.'],
  ['LLM-as-a-judge', 'Using a language model to score outputs against a defined rubric; it still needs calibration and bias checks.'],
  ['MCP', 'Model Context Protocol: an open protocol connecting AI applications to tools and contextual data.'],
  ['RAG', 'Retrieval-Augmented Generation: retrieve relevant evidence and include it in model context before generation.'],
  ['ROUGE', 'Recall-oriented overlap metric often used for summarization.'],
  ['Token', 'A unit of model input or output; token volume affects context use, latency, and cost.'],
  ['Accuracy', 'The share of predictions that are correct overall; misleading on imbalanced data because predicting the majority class can look strong while missing the minority.'],
  ['Precision', 'Of the items a model predicted positive, how many are actually positive; lowering it reduces false alarms.'],
  ['Recall', 'Of the items that are actually positive, how many the model found; lowering it reduces missed cases.'],
  ['F1 score', 'The harmonic mean of precision and recall, balancing false alarms against missed cases; useful on imbalanced data.'],
  ['AUC/ROC', 'Area under the ROC curve; measures how well a classifier separates classes across thresholds.'],
  ['Confusion matrix', 'A table of true positives, false negatives, false positives, and true negatives used to derive accuracy, precision, and recall.'],
  ['Overfitting', 'A model that memorizes training data, including its noise, so it performs well on training but poorly on new data.'],
  ['Underfitting', 'A model too simple to capture the underlying pattern, so it performs poorly on both training and new data.'],
  ['Bias-variance tradeoff', 'The tension between a too-simple model (high bias, underfits) and a too-flexible model (high variance, overfits); good generalization balances both.'],
  ['Hyperparameter', 'A configuration set before training — such as learning rate or temperature — that controls how the model learns; tuned, not learned from data.'],
  ['Parameter', 'A value the model learns from training data, such as weights; parameters are learned, hyperparameters are set.'],
  ['Ground truth', 'The known, correct labels or reference answers used to train and evaluate a model.'],
  ['Transfer learning', 'Reusing a model trained on one task as the starting point for a related task, reducing the data and compute needed.'],
  ['Fine-tuning', 'Further training a foundation model on task-specific labeled data to change persistent behavior, style, or task patterns.'],
  ['Continued pre-training', 'Extending a foundation model\u2019s pre-training on additional domain data to add broad knowledge; costlier than fine-tuning.'],
  ['RLHF', 'Reinforcement Learning from Human Feedback: aligning a model by training it to maximize human preference rankings.'],
  ['PEFT', 'Parameter-Efficient Fine-Tuning: adapting a model by updating only a small set of added or selected weights instead of all parameters; LoRA (Low-Rank Adaptation) is a common example.'],
  ['Amazon Augmented AI (A2I)', 'A service that routes low-confidence ML predictions to human reviewers and returns their decisions; it reviews production predictions rather than labeling training data.'],
  ['Zero-shot prompting', 'Asking a model to perform a task with no examples, relying on instructions alone.'],
  ['Few-shot prompting', 'Giving a model a small number of input-output examples in the prompt to steer its behavior.'],
  ['Chain-of-thought', 'Prompting a model to produce intermediate reasoning steps before a final answer; improves reasoning but is not proof of correctness.'],
  ['Prompt injection', 'An attack that hides instructions in the input or retrieved content to make the model ignore its system rules; indirect injection hides them in retrieved web content.'],
  ['Temperature', 'A sampling parameter controlling output randomness; lower values are more deterministic, higher values more varied and creative.'],
  ['Top-p', 'Nucleus sampling: choose the next token from the smallest set whose cumulative probability reaches p.'],
  ['Top-k', 'Sampling that restricts the next token to the k most probable candidates.'],
  ['Tokenization', 'Splitting text into tokens; one word is not always one token, and the split varies by model.'],
  ['Context window', 'The total token budget a model can attend to across input and output in a single request.'],
  ['Vector database', 'A data store optimized for storing and similarity-searching embeddings (numeric vectors).'],
  ['Vector index', 'A data structure that enables fast approximate nearest-neighbor search over embeddings.'],
  ['Semantic search', 'Retrieval by meaning — using embedding similarity — rather than exact keyword match.'],
  ['Exploratory data analysis (EDA)', 'Early analysis to understand data distributions, surface quality problems, and guide preprocessing before modeling.'],
  ['Feature engineering', 'Creating and selecting the input signals (features) a model can learn from.'],
  ['Feature store', 'A central repository for storing, versioning, and sharing features across training and serving.'],
  ['Data augmentation', 'Artificially expanding training data with transformations — such as rotation, cropping, or paraphrasing — to improve generalization.'],
  ['Model drift', 'Degradation of a deployed model\u2019s performance over time as the real world changes.'],
  ['Data drift', 'A change in the distribution of input data over time, degrading a deployed model\u2019s performance.'],
  ['Inference', 'Using a trained model to produce predictions on new data; training fits parameters, inference applies them.'],
  ['Supervised learning', 'Learning from labeled examples that map inputs to known outputs; includes classification and regression.'],
  ['Unsupervised learning', 'Learning structure from unlabeled data, such as clustering or dimensionality reduction.'],
  ['Reinforcement learning', 'Learning through trial and error, guided by rewards and penalties while acting in an environment.'],
  ['Classification', 'A supervised task that predicts a discrete category or label.'],
  ['Regression', 'A supervised task that predicts a continuous numeric value.'],
  ['Clustering', 'An unsupervised task that groups similar, unlabeled examples into natural clusters.'],
  ['Transformer', 'A neural architecture using self-attention that underlies most modern foundation and large language models.'],
  ['Latency', 'The time between a request and its response; a key discriminator between real-time and batch inference.'],
  ['Foundation model (FM)', 'A broad, pre-trained model adaptable to many downstream tasks.'],
  ['Large language model (LLM)', 'A large foundation model trained on text to understand and generate language.'],
  ['Knowledge base', 'A managed store of source documents that a RAG system retrieves from to ground model responses.'],
  ['Agent', 'A system that combines a model with goals, tools, memory, and orchestration to act across multiple steps.'],
  ['Tool', 'An external capability — such as an API or function — an agent calls to act beyond generating text.'],
  ['Orchestration', 'The logic that plans and sequences an agent\u2019s steps, deciding what to do next.'],
  ['Human-in-the-loop', 'A workflow where humans review, correct, or approve model outputs, especially for low-confidence or high-impact decisions.'],
  ['Model evaluation', 'Measuring model quality and responsibility using benchmark datasets, automatic metrics, and human review.'],
  ['Model distillation', 'Training a smaller student model to reproduce useful behavior from a larger teacher model, lowering cost and latency.'],
  ['Guardrails', 'Policies that filter harmful, denied, or sensitive content in model inputs and outputs; a policy layer that complements IAM and application controls.'],
  ['Model Cards', 'Structured documentation of a model\u2019s purpose, training data, evaluation, limitations, and intended use for reviewers.'],
]
