import type { Resource, StudyDay } from '../../core/types'

export const resources: Resource[] = [
  { id: 'exam-guide', title: 'Official AIF-C01 exam guide', url: 'https://docs.aws.amazon.com/aws-certification/latest/ai-practitioner-01/ai-practitioner-01.html', kind: 'Official AWS', assignedDate: '2026-09-22', duration: 'Reference', outcome: 'Remain the source of truth while checking revisions, scope, formats, and exam facts.' },
  { id: 'revisions', title: 'Official v1.1 revisions', url: 'https://docs.aws.amazon.com/aws-certification/latest/ai-practitioner-01/aif-01-revisions.html', kind: 'Official AWS', assignedDate: '2026-09-22', duration: '30 min', outcome: 'Confirm every newly added or changed objective through the app checklist.' },
  { id: 'scope', title: 'Official in-scope services', url: 'https://docs.aws.amazon.com/aws-certification/latest/ai-practitioner-01/aif-01-in-scope-services.html', kind: 'Official AWS', assignedDate: '2026-09-22', duration: '30 min', outcome: 'Confirm service boundaries instead of memorizing names.' },
  { id: 'skillbuilder', title: 'Official 20-question Practice Question Set', url: 'https://skillbuilder.aws/learn/4URFGY63KV/official-practice-question-set-aws-certified-ai-practitioner--aifc01--english/FVG43Y1PAX', kind: 'Official AWS', assignedDate: '2026-09-12', duration: '120 min including review', outcome: 'Use all 20 official questions as the calendar baseline, then complete a full error review without copying questions.' },
  { id: 'cloudcertprep', title: 'CloudCertPrep AIF-C01 practice', url: 'https://www.cloudcertprep.io/aws/aif-c01', kind: 'Third-party practice', assignedDate: '2026-09-20', duration: '120 min including initial review', outcome: 'Complete a 65-question simulation in 90 minutes, begin review, and verify disputed claims against official AWS sources.' },
  { id: 'dojo', title: 'Tutorials Dojo free sampler', url: 'https://portal.tutorialsdojo.com/courses/free-aws-certified-ai-practitioner-practice-exams-aif-c01-sampler/', kind: 'Third-party practice', assignedDate: '2026-09-23', duration: '60 min', outcome: 'Practice elimination and log every uncertain distinction.' },
  { id: 's3-vectors', title: 'Amazon S3 Vectors documentation', url: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-vectors.html', kind: 'Official AWS', assignedDate: '2026-09-21', duration: 'Targeted reference', outcome: 'Resolve relevant errors about vector buckets, indexes, and RAG use cases.' },
  { id: 'guardrails', title: 'Amazon Bedrock Guardrails documentation', url: 'https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html', kind: 'Official AWS', assignedDate: '2026-09-21', duration: 'Targeted reference', outcome: 'Resolve relevant errors about safety filters versus IAM and application validation.' },
  { id: 'agentcore', title: 'Amazon Bedrock AgentCore documentation', url: 'https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/what-is-bedrock-agentcore.html', kind: 'Official AWS', assignedDate: '2026-09-21', duration: 'Targeted reference', outcome: 'Resolve relevant errors about runtime, memory, identity, gateway, observability, and policy.' },
]

export const studyPlan: StudyDay[] = [
  { date: '2026-09-12', duration: '2h', capacityMinutes: 120, focus: 'Official baseline and full error review', outcome: 'Complete the AWS Skill Builder official 20-question set as the calendar baseline, then review every error and uncertainty.', resourceIds: ['skillbuilder'], activities: [{ id: 'official-20-question-baseline', type: 'practice', durationMinutes: 45 }, { id: 'official-baseline-error-review', type: 'study', durationMinutes: 75 }] },
  { date: '2026-09-13', duration: '2h', capacityMinutes: 120, focus: 'Domain 3: foundation model applications', outcome: 'Use the app guide to master FM selection, RAG, customization, and inference tradeoffs.', resourceIds: [], activities: [{ id: 'domain-3-selection-rag-customization', type: 'study', durationMinutes: 120 }] },
  { date: '2026-09-14', duration: '1h', capacityMinutes: 60, focus: 'Domain 3: prompts and evaluation', outcome: 'Use the app guide to practice prompting choices, evaluation approaches, and technical and business metrics.', resourceIds: [], activities: [{ id: 'domain-3-prompts-evaluation', type: 'study', durationMinutes: 60 }] },
  { date: '2026-09-15', duration: '1h', capacityMinutes: 60, focus: 'Domain 2: generative AI foundations', outcome: 'Use the app guide to review GenAI, token economics, context windows, and context engineering.', resourceIds: [], activities: [{ id: 'domain-2-genai-tokens-context', type: 'study', durationMinutes: 60 }] },
  { date: '2026-09-16', duration: '1h', capacityMinutes: 60, focus: 'Domain 1: AI and ML fundamentals', outcome: 'Use the app guide to differentiate lifecycle stages, learning types, inference, and metrics.', resourceIds: [], activities: [{ id: 'domain-1-lifecycle-learning-metrics', type: 'study', durationMinutes: 60 }] },
  { date: '2026-09-17', duration: '1h', capacityMinutes: 60, focus: 'Domain 4: responsible AI', outcome: 'Use the app guide to distinguish fairness, explainability, transparency, privacy, safety, and accountability.', resourceIds: [], activities: [{ id: 'domain-4-responsible-ai', type: 'study', durationMinutes: 60 }] },
  { date: '2026-09-18', duration: '1h', capacityMinutes: 60, focus: 'Domain 5: security and governance', outcome: 'Use the app guide to review security, compliance, governance, Guardrails, and agent controls.', resourceIds: [], activities: [{ id: 'domain-5-security-governance', type: 'study', durationMinutes: 60 }] },
  { date: '2026-09-19', duration: '2h', capacityMinutes: 120, focus: 'First app simulator', outcome: 'Run the first app 65-question simulation in 90 minutes, then classify errors for 30 minutes.', resourceIds: [], activities: [{ id: 'first-own-65-question-exam', type: 'full-exam', durationMinutes: 90 }, { id: 'first-own-exam-error-classification', type: 'study', durationMinutes: 30 }] },
  { date: '2026-09-20', duration: '2h', capacityMinutes: 120, focus: 'CloudCertPrep simulation', outcome: 'Run a CloudCertPrep 65-question simulation in 90 minutes, then begin the error review.', resourceIds: ['cloudcertprep'], activities: [{ id: 'cloudcertprep-65-question-exam', type: 'practice', durationMinutes: 90 }, { id: 'cloudcertprep-initial-review', type: 'study', durationMinutes: 30 }] },
  { date: '2026-09-21', duration: '1h', capacityMinutes: 60, focus: 'CloudCertPrep error review', outcome: 'Finish the CloudCertPrep error review and consult S3 Vectors, Guardrails, and AgentCore official documentation only where the errors require it.', resourceIds: ['cloudcertprep', 's3-vectors', 'guardrails', 'agentcore'], activities: [{ id: 'cloudcertprep-error-review', type: 'study', durationMinutes: 35 }, { id: 'targeted-official-documentation', type: 'study', durationMinutes: 25 }] },
  { date: '2026-09-22', duration: '1h', capacityMinutes: 60, focus: 'Official v1.1 and service scope check', outcome: 'Complete the app checklist against official revisions and in-scope services, using the exam guide as the source-of-truth reference.', resourceIds: ['revisions', 'scope', 'exam-guide'], activities: [{ id: 'official-v11-scope-checklist', type: 'study', durationMinutes: 60 }] },
  { date: '2026-09-23', duration: '1h', capacityMinutes: 60, focus: 'Tutorials Dojo timed sampler', outcome: 'Complete the free 20-question sampler in timed mode and record errors or uncertainty.', resourceIds: ['dojo'], activities: [{ id: 'dojo-20-question-timed-sampler', type: 'practice', durationMinutes: 60 }] },
  { date: '2026-09-24', duration: '1h', capacityMinutes: 60, focus: 'Weakest-domain practice', outcome: 'Use CloudCertPrep domain practice for the current weakest domain and record the distinctions still missed.', resourceIds: ['cloudcertprep'], activities: [{ id: 'cloudcertprep-weakest-domain-practice', type: 'practice', durationMinutes: 60 }] },
  { date: '2026-09-25', duration: '1h', capacityMinutes: 60, focus: 'Adaptive final review', outcome: 'Review adaptive weak topics, decision cues, the glossary, and accumulated mistakes; add no broad new material.', resourceIds: [], activities: [{ id: 'adaptive-cues-glossary-mistakes', type: 'study', durationMinutes: 60 }] },
  { date: '2026-09-26', duration: '2h', capacityMinutes: 120, focus: 'Second hard app simulator', outcome: 'Run the second hard app 65-question simulation in 90 minutes, then review for 30 minutes.', resourceIds: [], activities: [{ id: 'second-own-hard-65-question-exam', type: 'full-exam', durationMinutes: 90 }, { id: 'second-own-exam-review', type: 'study', durationMinutes: 30 }] },
  { date: '2026-09-27', duration: '30 min', capacityMinutes: 120, focus: 'Light final review only', outcome: 'Spend 20–30 minutes on compact cues and known mistakes only; add no new material.', resourceIds: [], activities: [{ id: 'light-final-review', type: 'study', durationMinutes: 30 }] },
]
