import { useEffect, useMemo, useState } from 'react'
import { Practice } from './components/Practice'
import { loadProgress, saveProgress } from './core/progress'
import type { Progress } from './core/types'
import { guide } from './certifications/aif-c01/guide'
import { aifPracticeModule, azureTransfers, domains, examFacts, glossary, practiceScoreDisclaimer, serviceMap } from './certifications/aif-c01/module'
import { resources, studyPlan } from './certifications/aif-c01/plan'

type View = 'catalog' | 'dashboard' | 'guide' | 'plan' | 'practice' | 'progress'

export default function App() {
  const [view, setView] = useState<View>('catalog')
  const [progress, setProgress] = useState<Progress>(() => loadProgress())
  const [storageOk, setStorageOk] = useState(true)
  useEffect(() => setStorageOk(saveProgress(progress)), [progress])
  const latest = progress.attempts.at(-1)
  const totalPlannedMinutes = studyPlan.flatMap((day) => day.activities).reduce((sum, activity) => sum + activity.durationMinutes, 0)
  const plannedDuration = `${Math.floor(totalPlannedMinutes / 60)}h ${totalPlannedMinutes % 60}m`
  const completedPlan = studyPlan.filter((day) => progress.completedPlanItems.includes(day.date)).length
  const missedTopics = useMemo(() => new Set(progress.attempts.flatMap((attempt) => attempt.questionIds.filter((id) => !attempt.answers[id]?.correct || attempt.answers[id]?.confused))).size, [progress.attempts])

  const navigate = (next: View) => { setView(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <div className="app-shell"><header><div className="brand"><span className="brand-mark">AWS</span><div><strong>Certification Study Lab</strong><small>Learn distinctions. Correct errors. Build confidence.</small></div></div><nav aria-label="Primary navigation">{(['catalog', 'dashboard', 'guide', 'plan', 'practice', 'progress'] as View[]).map((item) => <button key={item} className={view === item ? 'active' : ''} onClick={() => navigate(item)}>{item === 'catalog' ? 'Certifications' : item[0].toUpperCase() + item.slice(1)}</button>)}</nav></header>{!storageOk && <div className="storage-warning" role="alert">Progress could not be saved. Your browser may be blocking storage or have no available space.</div>}<main id="main">
    {view === 'catalog' && <section className="hero"><div className="hero-copy"><p className="eyebrow">Public · local-first · no account</p><h1>Study the AWS decision, not just the service name.</h1><p>A reusable certification platform built around concise guidance, original practice, error-driven correction, and a final weak-point review.</p><button className="primary large" onClick={() => navigate('dashboard')}>Open AIF-C01 module</button></div><div className="catalog-grid"><article className="cert-card active-cert"><span className="status-pill">Available</span><h2>AWS Certified AI Practitioner</h2><p>AIF-C01 · Guide v1.1</p><div className="progress-bar"><span style={{ width: `${(completedPlan / studyPlan.length) * 100}%` }} /></div><small>{completedPlan}/{studyPlan.length} study days complete</small></article><article className="cert-card future"><span className="status-pill">Planned</span><h2>AWS Certified Cloud Practitioner</h2><p>CLF-C02 · Future module</p><small>The shared guide, plan, practice, and progress engine is ready for another content module.</small></article></div></section>}
    {view === 'dashboard' && <><section className="dashboard-hero"><div><p className="eyebrow">AIF-C01 · Exam guide v{examFacts.version} · Published {examFacts.publicationDate}</p><h1>AWS Certified AI Practitioner</h1><p>Exam date: <strong>September 27, 2026</strong> · Planned activity: <strong>{plannedDuration}</strong></p></div><button className="primary" onClick={() => navigate('practice')}>{progress.attempts.length ? 'Continue practice' : 'Start optional app diagnostic'}</button></section><section className="fact-grid">{[['Questions', examFacts.questions], ['Time', `${examFacts.minutes} min`], ['Scored', examFacts.scored], ['Unscored', examFacts.unscored], ['Passing score', examFacts.passingScore]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><p className="callout">{practiceScoreDisclaimer}</p><section className="panel"><div className="section-heading"><div><p className="eyebrow">Weighted blueprint</p><h2>Spend time where the exam does</h2></div></div><div className="domain-list">{domains.map((domain) => <article key={domain.id}><div className="weight" style={{ '--weight': `${domain.weight}%` } as React.CSSProperties}><strong>{domain.weight}%</strong></div><div><h3>{domain.id} · {domain.title}</h3><p>{domain.objectives.join(' · ')}</p></div></article>)}</div></section><section className="quick-grid"><button onClick={() => navigate('guide')}><strong>Read the concise guide</strong><span>Five weighted domains + v1.1 markers</span></button><button onClick={() => navigate('plan')}><strong>Follow today’s plan</strong><span>Dated through exam day</span></button><button onClick={() => navigate('progress')}><strong>Review weak points</strong><span>{missedTopics} missed or confused topics in history</span></button></section></>}
    {view === 'guide' && <><section className="page-title"><p className="eyebrow">Concise evolving guide</p><h1>Recognize the requirement, then choose the boundary.</h1><p>Use this guide to correct errors after practice. v1.1 markers highlight materially changed scope.</p></section>{guide.map((section) => { const domain = domains.find((item) => item.id === section.domain)!; return <section className="panel guide-domain" key={section.domain}><div className="domain-title"><span>{domain.weight}%</span><div><p className="eyebrow">{section.domain}</p><h2>{domain.title}</h2></div></div><p className="lead">{section.summary}</p><div className="v11"><strong>What changed in v1.1</strong><ul>{section.v11.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="concept-grid">{section.concepts.map((concept) => <article key={concept.title}><h3>{concept.title}</h3><p>{concept.body}</p>{concept.cue && <p className="cue"><strong>If the question says… think…</strong> {concept.cue}</p>}{concept.notThis && <p className="not-this"><strong>Not this:</strong> {concept.notThis}</p>}</article>)}</div></section>})}<ReferenceTables /></>}
    {view === 'plan' && <section><div className="page-title"><p className="eyebrow">September 12–27, 2026 · {plannedDuration} planned</p><h1>An error-driven study plan</h1><p>Javier López’s loop is built in: keep a concise guide, practice questions, correct the guide from errors, and finish on weak points rather than passive rereading.</p><p className="callout">The AWS Skill Builder official 20-question set is the required calendar baseline on September 12. The app’s original 20-question diagnostic remains available as an optional extra and is not another scheduled block.</p></div><div className="plan-list">{studyPlan.map((day) => { const dayResources = resources.filter((resource) => day.resourceIds.includes(resource.id)); const checked = progress.completedPlanItems.includes(day.date); return <article className={checked ? 'done' : ''} key={day.date}><label className="plan-check"><input type="checkbox" checked={checked} onChange={() => setProgress((current) => ({ ...current, completedPlanItems: checked ? current.completedPlanItems.filter((date) => date !== day.date) : [...current.completedPlanItems, day.date] }))} /><span><strong>{new Date(`${day.date}T12:00:00`).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}</strong><small>{day.duration}</small></span></label><div><h2>{day.focus}</h2><p>{day.outcome}</p><ul className="activity-list">{day.activities.map((activity) => <li key={activity.id}>{activity.durationMinutes} min · {activity.type === 'full-exam' ? 'Full timed exam' : activity.type}</li>)}</ul>{dayResources.map((resource) => { const resourceKey = `resource:${resource.id}`; const resourceDone = progress.completedPlanItems.includes(resourceKey); return <div className="resource" key={resource.id}><div><span className={resource.kind === 'Official AWS' ? 'official' : 'third-party'}>{resource.kind}</span><a href={resource.url} target="_blank" rel="noreferrer">{resource.title}<span aria-hidden="true"> ↗</span></a><small>{resource.duration} · Expected outcome: {resource.outcome}</small><label className="resource-check"><input type="checkbox" checked={resourceDone} onChange={() => setProgress((current) => ({ ...current, completedPlanItems: resourceDone ? current.completedPlanItems.filter((item) => item !== resourceKey) : [...current.completedPlanItems, resourceKey] }))} />Resource completed</label></div><textarea aria-label={`Optional score or error notes for ${resource.title}`} placeholder="Optional score / error notes" value={progress.resourceNotes[resource.id] ?? ''} onChange={(event) => setProgress((current) => ({ ...current, resourceNotes: { ...current.resourceNotes, [resource.id]: event.target.value } }))} /></div>})}</div></article>})}</div><p className="source-note">Third-party practice is for independent calibration. Do not copy questions; verify disputed facts against official AWS sources.</p></section>}
    {view === 'practice' && <Practice certification={aifPracticeModule} progress={progress} setProgress={setProgress} />}
    {view === 'progress' && <section><div className="page-title"><p className="eyebrow">Stored only in this browser</p><h1>Progress and attempt history</h1><p>{completedPlan}/{studyPlan.length} plan days complete · {progress.attempts.length} attempts · {missedTopics} current review topics.</p></div>{latest ? <div className="history-list">{[...progress.attempts].reverse().map((attempt) => <article key={attempt.id}><div><strong>{attempt.mode}</strong><span>{new Date(attempt.completedAt).toLocaleString()}</span></div><strong>{attempt.practicePercent}%</strong><small>{Object.values(attempt.answers).filter((answer) => answer.correct).length}/{attempt.questionIds.length} correct · practice percentage</small></article>)}</div> : <div className="empty-state"><h2>No completed attempts yet</h2><p>The optional app diagnostic can create an adaptive weak-domain baseline; the calendar baseline is the official Skill Builder set.</p><button className="primary" onClick={() => navigate('practice')}>Open practice</button></div>}<details className="data-controls"><summary>Local data controls</summary><p>Progress is stored in localStorage on this device. Clearing it cannot be undone.</p><button className="danger" onClick={() => { if (window.confirm('Clear all locally stored study progress?')) setProgress({ version: 1, attempts: [], completedPlanItems: [], resourceNotes: {} }) }}>Clear local progress</button></details></section>}
  </main><footer><p>Independent educational project. AWS product names and trademarks belong to Amazon Web Services, Inc. Not affiliated with or endorsed by AWS.</p><p>{aifPracticeModule.questions.length} original questions · No exam dumps · Official AWS documentation is the source of truth.</p></footer></div>
}

function ReferenceTables() {
  return <><section className="panel"><p className="eyebrow">Recognition over recall</p><h2>AWS service map</h2><div className="table-wrap"><table><thead><tr><th>Need</th><th>Think</th><th>Boundary</th></tr></thead><tbody>{serviceMap.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></section><section className="panel"><p className="eyebrow">Use prior knowledge carefully</p><h2>Azure-to-AWS transfer notes</h2><div className="table-wrap"><table><thead><tr><th>Azure anchor</th><th>AWS anchor</th><th>Transfer note</th></tr></thead><tbody>{azureTransfers.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></section><section className="panel"><p className="eyebrow">Acronym support</p><h2>Compact glossary</h2><dl className="glossary">{glossary.map(([term, definition]) => <div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl></section></>
}
